import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Online Dukaan</title>
        <meta name="description" content="Generated by create next app"></meta>
      </Head>
      <h1 className="text-3xl font-bold">Online Dukaan</h1>
    </div>
  );
}
